/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import java.math.BigDecimal;
import org.openapitools.model.Category;
import org.openapitools.model.ErrorResponse;
import org.springframework.lang.Nullable;
import org.openapitools.model.OrderCreateInput;
import org.openapitools.model.OrderStatusUpdateInput;
import org.openapitools.model.Product;
import org.openapitools.model.ProductCreateInput;
import org.openapitools.model.ProductListResponse;
import org.openapitools.model.ProductUpdateInput;
import org.openapitools.model.Seller;
import org.openapitools.model.SellerCreateInput;
import org.openapitools.model.SellerUpdateInput;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-08T10:47:06.539361157Z[Etc/UTC]", comments = "Generator version: 7.22.0-SNAPSHOT")
@Validated
@Tag(name = "Categories", description = "Category endpoints")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_API_V1_CATEGORIES_CATEGORY_ID_PRODUCTS_GET = "/api/v1/categories/{categoryId}/products";
    /**
     * GET /api/v1/categories/{categoryId}/products : Get products of a category
     *
     * @param categoryId  (required)
     * @return Products of category (status code 200)
     */
    @Operation(
        operationId = "apiV1CategoriesCategoryIdProductsGet",
        summary = "Get products of a category",
        tags = { "Categories" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Products of category")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_CATEGORIES_CATEGORY_ID_PRODUCTS_GET
    )
    default ResponseEntity<Void> apiV1CategoriesCategoryIdProductsGet(
        @Parameter(name = "categoryId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") UUID categoryId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_CATEGORIES_GET = "/api/v1/categories";
    /**
     * GET /api/v1/categories : Get categories list
     *
     * @return Categories list (status code 200)
     */
    @Operation(
        operationId = "apiV1CategoriesGet",
        summary = "Get categories list",
        tags = { "Categories" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Categories list")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_CATEGORIES_GET
    )
    default ResponseEntity<Void> apiV1CategoriesGet(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_ORDERS_GET = "/api/v1/orders";
    /**
     * GET /api/v1/orders : Get orders list
     *
     * @param productId  (optional)
     * @param customerName  (optional)
     * @return Orders list (status code 200)
     */
    @Operation(
        operationId = "apiV1OrdersGet",
        summary = "Get orders list",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Orders list")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_ORDERS_GET
    )
    default ResponseEntity<Void> apiV1OrdersGet(
        @Parameter(name = "productId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "productId", required = false) @Nullable UUID productId,
        @Parameter(name = "customerName", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "customerName", required = false) @Nullable String customerName
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_ORDERS_ID_DELETE = "/api/v1/orders/{id}";
    /**
     * DELETE /api/v1/orders/{id} : Delete order
     *
     * @param id Order id (required)
     * @return Order deleted (status code 204)
     */
    @Operation(
        operationId = "apiV1OrdersIdDelete",
        summary = "Delete order",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Order deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ApiApi.PATH_API_V1_ORDERS_ID_DELETE
    )
    default ResponseEntity<Void> apiV1OrdersIdDelete(
        @Parameter(name = "id", description = "Order id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_ORDERS_ID_GET = "/api/v1/orders/{id}";
    /**
     * GET /api/v1/orders/{id} : Get order by id
     *
     * @param id Order id (required)
     * @return Order details (status code 200)
     *         or Order not found (status code 404)
     */
    @Operation(
        operationId = "apiV1OrdersIdGet",
        summary = "Get order by id",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Order details"),
            @ApiResponse(responseCode = "404", description = "Order not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_ORDERS_ID_GET
    )
    default ResponseEntity<Void> apiV1OrdersIdGet(
        @Parameter(name = "id", description = "Order id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_ORDERS_ID_STATUS_PATCH = "/api/v1/orders/{id}/status";
    /**
     * PATCH /api/v1/orders/{id}/status : Update order status
     *
     * @param id Order id (required)
     * @param orderStatusUpdateInput  (required)
     * @return Order status updated (status code 200)
     *         or Invalid body (status code 400)
     */
    @Operation(
        operationId = "apiV1OrdersIdStatusPatch",
        summary = "Update order status",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Order status updated"),
            @ApiResponse(responseCode = "400", description = "Invalid body")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = ApiApi.PATH_API_V1_ORDERS_ID_STATUS_PATCH,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> apiV1OrdersIdStatusPatch(
        @Parameter(name = "id", description = "Order id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "OrderStatusUpdateInput", description = "", required = true) @Valid @RequestBody OrderStatusUpdateInput orderStatusUpdateInput
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_ORDERS_POST = "/api/v1/orders";
    /**
     * POST /api/v1/orders : Create order
     *
     * @param orderCreateInput  (required)
     * @return Order created (status code 201)
     *         or Invalid body (status code 400)
     */
    @Operation(
        operationId = "apiV1OrdersPost",
        summary = "Create order",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Order created"),
            @ApiResponse(responseCode = "400", description = "Invalid body")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_API_V1_ORDERS_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> apiV1OrdersPost(
        @Parameter(name = "OrderCreateInput", description = "", required = true) @Valid @RequestBody OrderCreateInput orderCreateInput
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_PRODUCTS_GET = "/api/v1/products";
    /**
     * GET /api/v1/products : Get products list
     * Returns a paginated list of products with filtering, sorting and search options.
     *
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 10)
     * @param sortBy  (optional)
     * @param order  (optional)
     * @param category  (optional)
     * @param sellerId  (optional)
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @param search  (optional)
     * @param acceptLanguage  (optional)
     * @return Products list (status code 200)
     *         or Invalid query/body (status code 400)
     */
    @Operation(
        operationId = "apiV1ProductsGet",
        summary = "Get products list",
        description = "Returns a paginated list of products with filtering, sorting and search options.",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Products list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProductListResponse.class)),
                @Content(mediaType = "application/xml", schema = @Schema(implementation = ProductListResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid query/body", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class)),
                @Content(mediaType = "application/xml", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_PRODUCTS_GET,
        produces = { "application/json", "application/xml" }
    )
    default ResponseEntity<ProductListResponse> apiV1ProductsGet(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "10") Integer limit,
        @Parameter(name = "sortBy", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sortBy", required = false) @Nullable String sortBy,
        @Parameter(name = "order", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order", required = false) @Nullable String order,
        @Parameter(name = "category", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "category", required = false) @Nullable String category,
        @Parameter(name = "sellerId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sellerId", required = false) @Nullable UUID sellerId,
        @Parameter(name = "minPrice", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "minPrice", required = false) @Nullable BigDecimal minPrice,
        @Parameter(name = "maxPrice", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "maxPrice", required = false) @Nullable BigDecimal maxPrice,
        @Parameter(name = "search", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "search", required = false) @Nullable String search,
        @Parameter(name = "Accept-Language", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "Accept-Language", required = false) @Nullable String acceptLanguage
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"total\" : 2, \"data\" : [ { \"createdAt\" : \"mardi 7 avril 2026 à 16:35:48 UTC\", \"thumbnail\" : \"https://example.com/mouse.jpg\", \"price\" : 1700, \"name\" : \"Mouse X\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"category\" : \"electronics\" }, { \"createdAt\" : \"mardi 7 avril 2026 à 16:35:48 UTC\", \"thumbnail\" : \"https://example.com/mouse.jpg\", \"price\" : 1700, \"name\" : \"Mouse X\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"category\" : \"electronics\" } ], \"_links\" : { \"key\" : \"\" }, \"limit\" : 10, \"page\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<null> <total>2</total> <page>1</page> <limit>10</limit> <_links>UNDEFINED_EXAMPLE_VALUE</_links> </null>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"BODY_NOT_VALID\", \"details\" : \"Only price and stock can be updated\", \"message\" : \"Invalid request body\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_PRODUCTS_ID_CATEGORY_GET = "/api/v1/products/{id}/category";
    /**
     * GET /api/v1/products/{id}/category : Get category of a product
     *
     * @param id Product id (required)
     * @return Category of the product (status code 200)
     */
    @Operation(
        operationId = "apiV1ProductsIdCategoryGet",
        summary = "Get category of a product",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Category of the product", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Category.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_PRODUCTS_ID_CATEGORY_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Category> apiV1ProductsIdCategoryGet(
        @Parameter(name = "id", description = "Product id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"name\" : \"electronics\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_PRODUCTS_ID_DELETE = "/api/v1/products/{id}";
    /**
     * DELETE /api/v1/products/{id} : Delete product
     *
     * @param id Product id (required)
     * @return Product deleted (status code 204)
     *         or Product not found (status code 404)
     */
    @Operation(
        operationId = "apiV1ProductsIdDelete",
        summary = "Delete product",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Product deleted"),
            @ApiResponse(responseCode = "404", description = "Product not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ApiApi.PATH_API_V1_PRODUCTS_ID_DELETE
    )
    default ResponseEntity<Void> apiV1ProductsIdDelete(
        @Parameter(name = "id", description = "Product id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_PRODUCTS_ID_GET = "/api/v1/products/{id}";
    /**
     * GET /api/v1/products/{id} : Get product by id
     *
     * @param id Product id (required)
     * @return Product details (status code 200)
     *         or Resource not found (status code 404)
     */
    @Operation(
        operationId = "apiV1ProductsIdGet",
        summary = "Get product by id",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Product details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Product.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_PRODUCTS_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Product> apiV1ProductsIdGet(
        @Parameter(name = "id", description = "Product id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"seller\" : { \"rating\" : 4.7, \"storeName\" : \"Tech Store\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"createdAt\" : \"createdAt\", \"images\" : [ \"images\", \"images\" ], \"_links\" : { \"key\" : \"\" }, \"price\" : 1700, \"name\" : \"Mouse X\", \"description\" : \"Wireless mouse for office and gaming\", \"currency\" : \"USD\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"stock\" : 7, \"category\" : { \"name\" : \"electronics\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"BODY_NOT_VALID\", \"details\" : \"Only price and stock can be updated\", \"message\" : \"Invalid request body\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_PRODUCTS_ID_PATCH = "/api/v1/products/{id}";
    /**
     * PATCH /api/v1/products/{id} : Update product price and stock
     *
     * @param id Product id (required)
     * @param productUpdateInput  (required)
     * @return Product updated (status code 200)
     *         or Invalid body/params (status code 400)
     *         or Product not found (status code 404)
     */
    @Operation(
        operationId = "apiV1ProductsIdPatch",
        summary = "Update product price and stock",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Product updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Product.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid body/params", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Product not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = ApiApi.PATH_API_V1_PRODUCTS_ID_PATCH,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Product> apiV1ProductsIdPatch(
        @Parameter(name = "id", description = "Product id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "ProductUpdateInput", description = "", required = true) @Valid @RequestBody ProductUpdateInput productUpdateInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"seller\" : { \"rating\" : 4.7, \"storeName\" : \"Tech Store\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"createdAt\" : \"createdAt\", \"images\" : [ \"images\", \"images\" ], \"_links\" : { \"key\" : \"\" }, \"price\" : 1700, \"name\" : \"Mouse X\", \"description\" : \"Wireless mouse for office and gaming\", \"currency\" : \"USD\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"stock\" : 7, \"category\" : { \"name\" : \"electronics\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"BODY_NOT_VALID\", \"details\" : \"Only price and stock can be updated\", \"message\" : \"Invalid request body\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"BODY_NOT_VALID\", \"details\" : \"Only price and stock can be updated\", \"message\" : \"Invalid request body\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_PRODUCTS_ID_SELLER_GET = "/api/v1/products/{id}/seller";
    /**
     * GET /api/v1/products/{id}/seller : Get seller of a product
     *
     * @param id Product id (required)
     * @return Seller of the product (status code 200)
     */
    @Operation(
        operationId = "apiV1ProductsIdSellerGet",
        summary = "Get seller of a product",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Seller of the product", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Seller.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_PRODUCTS_ID_SELLER_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Seller> apiV1ProductsIdSellerGet(
        @Parameter(name = "id", description = "Product id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"Tuesday, April 7, 2026 at 4:35:48 PM UTC\", \"address\" : { \"country\" : \"Morocco\", \"zipCode\" : \"20000\", \"city\" : \"Casablanca\", \"street\" : \"Rue 10\" }, \"phone\" : \"+212600000000\", \"rating\" : 4.7, \"storeName\" : \"Tech Store\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"email\" : \"techstore@example.com\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_PRODUCTS_POST = "/api/v1/products";
    /**
     * POST /api/v1/products : Create a product
     *
     * @param productCreateInput  (required)
     * @return Product created (status code 201)
     *         or Invalid body (status code 400)
     */
    @Operation(
        operationId = "apiV1ProductsPost",
        summary = "Create a product",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Product created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Product.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid body", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_API_V1_PRODUCTS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Product> apiV1ProductsPost(
        @Parameter(name = "ProductCreateInput", description = "", required = true) @Valid @RequestBody ProductCreateInput productCreateInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"seller\" : { \"rating\" : 4.7, \"storeName\" : \"Tech Store\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"createdAt\" : \"createdAt\", \"images\" : [ \"images\", \"images\" ], \"_links\" : { \"key\" : \"\" }, \"price\" : 1700, \"name\" : \"Mouse X\", \"description\" : \"Wireless mouse for office and gaming\", \"currency\" : \"USD\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"stock\" : 7, \"category\" : { \"name\" : \"electronics\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"BODY_NOT_VALID\", \"details\" : \"Only price and stock can be updated\", \"message\" : \"Invalid request body\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_SELLERS_GET = "/api/v1/sellers";
    /**
     * GET /api/v1/sellers : Get sellers list
     *
     * @return Sellers list (status code 200)
     */
    @Operation(
        operationId = "apiV1SellersGet",
        summary = "Get sellers list",
        tags = { "Sellers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Sellers list")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_SELLERS_GET
    )
    default ResponseEntity<Void> apiV1SellersGet(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_SELLERS_ID_DELETE = "/api/v1/sellers/{id}";
    /**
     * DELETE /api/v1/sellers/{id} : Delete seller
     *
     * @param id Seller id (required)
     * @return Seller deleted (status code 204)
     */
    @Operation(
        operationId = "apiV1SellersIdDelete",
        summary = "Delete seller",
        tags = { "Sellers" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Seller deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ApiApi.PATH_API_V1_SELLERS_ID_DELETE
    )
    default ResponseEntity<Void> apiV1SellersIdDelete(
        @Parameter(name = "id", description = "Seller id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_SELLERS_ID_GET = "/api/v1/sellers/{id}";
    /**
     * GET /api/v1/sellers/{id} : Get seller by id
     *
     * @param id Seller id (required)
     * @return Seller details (status code 200)
     *         or Seller not found (status code 404)
     */
    @Operation(
        operationId = "apiV1SellersIdGet",
        summary = "Get seller by id",
        tags = { "Sellers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Seller details"),
            @ApiResponse(responseCode = "404", description = "Seller not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_SELLERS_ID_GET
    )
    default ResponseEntity<Void> apiV1SellersIdGet(
        @Parameter(name = "id", description = "Seller id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_SELLERS_ID_PATCH = "/api/v1/sellers/{id}";
    /**
     * PATCH /api/v1/sellers/{id} : Update seller except email
     *
     * @param id Seller id (required)
     * @param sellerUpdateInput  (required)
     * @return Seller updated (status code 200)
     *         or Invalid body (status code 400)
     *         or Seller not found (status code 404)
     */
    @Operation(
        operationId = "apiV1SellersIdPatch",
        summary = "Update seller except email",
        tags = { "Sellers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Seller updated"),
            @ApiResponse(responseCode = "400", description = "Invalid body"),
            @ApiResponse(responseCode = "404", description = "Seller not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = ApiApi.PATH_API_V1_SELLERS_ID_PATCH,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> apiV1SellersIdPatch(
        @Parameter(name = "id", description = "Seller id", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "SellerUpdateInput", description = "", required = true) @Valid @RequestBody SellerUpdateInput sellerUpdateInput
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_SELLERS_POST = "/api/v1/sellers";
    /**
     * POST /api/v1/sellers : Create seller
     *
     * @param sellerCreateInput  (required)
     * @return Seller created (status code 201)
     *         or Invalid body (status code 400)
     */
    @Operation(
        operationId = "apiV1SellersPost",
        summary = "Create seller",
        tags = { "Sellers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Seller created"),
            @ApiResponse(responseCode = "400", description = "Invalid body")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_API_V1_SELLERS_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> apiV1SellersPost(
        @Parameter(name = "SellerCreateInput", description = "", required = true) @Valid @RequestBody SellerCreateInput sellerCreateInput
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_API_V1_SELLERS_SELLER_ID_PRODUCTS_GET = "/api/v1/sellers/{sellerId}/products";
    /**
     * GET /api/v1/sellers/{sellerId}/products : Get products of a seller
     *
     * @param sellerId  (required)
     * @return Products of seller (status code 200)
     */
    @Operation(
        operationId = "apiV1SellersSellerIdProductsGet",
        summary = "Get products of a seller",
        tags = { "Sellers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Products of seller")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_API_V1_SELLERS_SELLER_ID_PRODUCTS_GET
    )
    default ResponseEntity<Void> apiV1SellersSellerIdProductsGet(
        @Parameter(name = "sellerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sellerId") UUID sellerId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
